
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ae_project'
version: '1.0.0'
config-version: 2

# This setting configures for multiple use variables
vars:
  # Conversion channel names
  paid_click: "paid_click"
  paid_impression: "paid_impression"
  organic_click: "organic_click"
  direct: "direct"
  other: "other"

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

seeds:
  +schema: sources
  
models:
  staging:
    +schema: sources
    materialized: ephemeral
    +tags: ['staging']
  tier1_raw:
    +schema: tier1_raw
    materialized: table
    +tags: ['tier1_raw','tier1', 'raw', 'data_layer']
  tier2_curated:
    +schema: tier2_curated
    materialized: table
    +tags: ['tier2_curated','tier2', 'integration', 'curated']
  tier3_consumption:
    +schema: tier3_consumption
    materialized: table
    +tags: ['tier3_consumption','tier3', 'ready_for_reporting', 'consumption']
